;1、域名组
ruleset=📢 WIFI calling,https://github.com/xiritm168/xiritm168/raw/refs/heads/main/WiFicalling.list
ruleset=🎮 FCM推送,https://github.com/xiritm168/xiritm168/raw/refs/heads/main/FCM.list
ruleset=👽 AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=👽 AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI2.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=👯‍♂️ 社交,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=👯‍♂️ 社交,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list
ruleset=👯‍♂️ 社交,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/YouTube.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.list
ruleset=🛸 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=🛸 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleVoice/GoogleVoice.list
ruleset=🍎 苹果微软,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=🍎 苹果微软,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 国内流量,[]GEOIP,CN
ruleset=🌍 国外流量,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=🌍 国外流量,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外流量,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ZhihuAds/ZhihuAds.list
ruleset=🐟 漏网之鱼,[]FINAL

; === 调试版配置 (用于排查是否有节点) ===
custom_proxy_group=✈️ 手动选择`select`DIRECT,.*
custom_proxy_group=♻️ 自动选择`select`DIRECT,.*
custom_proxy_group=港台日新韩自动`select`DIRECT,.*

custom_proxy_group=🎮 FCM推送`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=📢 WIFI calling`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=👽 AI`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=👯‍♂️ 社交`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=📘 GitHub`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🛸 谷歌服务`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🙋 Telegram`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=📺 流媒体`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🍎 苹果微软`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🌍 国外流量`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🎯 国内流量`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🐟 漏网之鱼`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*
custom_proxy_group=🛑 广告拦截`select`DIRECT,♻️ 自动选择,✈️ 手动选择,.*

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
